version: '3.3'
services:
  activityrankwebsite:
    container_name: activityRankWebsite
    restart: always
    build: .
    volumes:
      - ./src:/usr/src/app
      #- /usr/src/app/node_modules
    command: npm run production
    ports:
      - "3006:3006"
